# Generated by Django 5.1.6 on 2025-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='busy',
            new_name='is_busy',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='responded',
            new_name='is_sent',
        ),
        migrations.RenameField(
            model_name='receptivityresponse',
            old_name='timestamp',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='receptivityresponse',
            name='receptive',
        ),
        migrations.AddField(
            model_name='receptivityresponse',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receptivityresponse',
            name='is_determined_to_adhere',
            field=models.BooleanField(default=False),
        ),
    ]
