# Generated by Django 5.1.6 on 2025-03-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_busy_context_is_busy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='is_busy',
        ),
        migrations.AddField(
            model_name='context',
            name='ongoing_task',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='sleep_hours',
            field=models.FloatField(blank=True, default=7.0, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='work_hours',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='social_environment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
