# Generated by Django 5.1.6 on 2025-03-14 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_context_is_busy_context_ongoing_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='social_environment',
            new_name='device_type',
        ),
        migrations.RenameField(
            model_name='context',
            old_name='ongoing_task',
            new_name='ongoing_activity',
        ),
        migrations.RemoveField(
            model_name='context',
            name='sleep_hours',
        ),
        migrations.RemoveField(
            model_name='context',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='context',
            name='connection_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='is_appropriate_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='context',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='context',
            name='is_silent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='context',
            name='location_distraction_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='motivation_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='surrounding_people',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='surrounding_people_distraction_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptivityresponse',
            name='is_perceived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='context',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.notification'),
        ),
    ]
