# Generated by Django 5.1.6 on 2025-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_social_environment_context_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='sleep_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='work_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
