# Generated by Django 5.1.6 on 2025-03-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_context_sleep_hours_context_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptivityresponse',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
