# Generated by Django 5.1.6 on 2025-03-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_one_signal_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='one_signal_player_id',
            new_name='telegram_id',
        ),
    ]
