# Generated by Django 5.1.6 on 2025-03-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_one_signal_player_id_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sleep_hours',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_hours',
        ),
    ]
